apiVersion: v1
kind: Service
metadata:
    name: "aksbanking-5741"
    labels:
        app: "aksbanking-5741"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksbanking-5741"